server:
  port: 8003
spring:
  application:
    name: asian-games-system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/asian-games-system?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
