server:
  port: 8004
spring:
  application:
    name: asian-games-system-competition
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 020929Fzz...
    url: jdbc:mysql://43.142.253.194:3306/asian-games-system?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 43.142.253.194
    port: 6379
    password: 123456
    database: 0
    timeout: 10000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl