spring:
  profiles:
    active: prod
  application:
    name: asian-games-system-personnel
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 3172029811@qq.com
    password: llfcopdlqufzddgd
    protocol: smtp
    nickname: 亚运会官方
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: xiaoMing
    properties.mail.display.sendname: xiaoming
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
