spring:
  profiles:
    active: prod
  application:
    name: asian-games-system-news
  rabbitmq:
    host: 43.142.253.194
    port: 5672
    username: admin
    password: 123



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
