spring:
  application:
    name: asian-games-system-file
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://root:root@43.142.253.194:27017/asian-games-system?authSource=admin
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fdfs:
  connect-timeout: 30
  tracker-list: 192.168.91.136:22122
  so-timeout: 30